### ISSUE TITLE
I can't auth it.

### ISSUE THREAD

**Issue by Karibura-Cyber** [revoxhere/duco-rest-api#12]
When I request it's say " {"message":"Wrong captcha score","success":false} "

What is captcha score and how can I get it?

**Comment by jisus-17** [comment]
thanks to the duinocoin staff you can't

**Comment by revoxhere** [comment]
XD?

**Comment by quocbao238** [comment]
@revoxhere Do you have any solution?
I building application Duino Wallet . How can i use this api auth ?
