### ISSUE TITLE
The requests to the API seem to be blacklisted

### ISSUE THREAD

**Issue by snakeye** [revoxhere/duco-rest-api#14]
Hello!

I'm pulling the data about my balance from the API endpoint `https://server.duinocoin.com/v3/users/` with the minute cron job. However, the script stopped working a few days ago. Now I'm getting the connection timeout like my server was put on the blacklist. The same request from my local machine passes fine. How could I solve the issue taking in account that the server's API address can not be changed easily?

**Comment by revoxhere** [comment]
E-mail/DM me the IP address of your server. It seems like it's permanently blocked for some reasons as temp bans expire after a few hours.

**Comment by revoxhere** [comment]
Solved via email
