### ISSUE TITLE
Error 308 (permanent redirect) while attempting an automated transaction using java

### ISSUE THREAD

**Issue by KosmicDaKerbal** [revoxhere/duco-rest-api#17]
![image](https://github.com/user-attachments/assets/e2bdd03a-ba16-4bfe-9929-325d092a18e9)

The transaction url works perfectly well on a browser, but gives an error 308 if used with java.
![image](https://github.com/user-attachments/assets/10390d7d-6be6-44ef-b56d-842ac39cf56f)
i use the following headers.

i do not understand whats the problem.. please help

**Comment by revoxhere** [comment]
See https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308
This is not an issue on our side.
